### ISSUE TITLE
[Angular bug] correct splash page display error

### ISSUE THREAD

**Issue by AndrewGoldstein** [ssravi/fifty-hypes#5]
@fromtheothershore @mhuerster
Needed: code changes to eliminate the strange formatting on splash page

![screen shot 2015-03-08 at 11 58 09 am](https://cloud.githubusercontent.com/assets/4494708/6547079/6f099b6a-c58a-11e4-9bc1-97ded42cb1bf.png)

**Comment by AndrewGoldstein** [comment]
@mhuerster does this have anything to do with https://github.com/ssravi/fifty-hypes/pull/2 ?

**Comment by andrewyu0** [comment]
moved the template to index.html instead of using `templateUrl` in `drawStates.js`. This works and fixes the issue for now, since we have the data we need scoped on the page.

**Comment by AndrewGoldstein** [comment]
@andrewcyu nice work!
